version: "3.9"

services:
  api:
    container_name: "social-buying"
    image: cosmtrek/air:latest
    restart: unless-stopped
    ports:
      - "3005:3000"
    working_dir: /app
    volumes:
      - ./:/app/
      - tmp:/app/tmp
      - ./.air.toml:/.air.toml


volumes:
  tmp: